
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPRINTFleftIDENTIFIERCOMMA FLOAT IDENTIFIER INT LEFT_PARENTESIS PRINTF RIGHT_PARENTESIS SEMICOLON STRINGstatement : PRINTF LEFT_PARENTESIS first_arg additional_args RIGHT_PARENTESIS SEMICOLONfirst_arg : STRINGadditional_args : COMMA arg additional_args\n                       | COMMA arg\n                       | emptyempty :arg : INT\n           | FLOAT\n           | STRING\n           | IDENTIFIER'
    
_lr_action_items = {'PRINTF':([0,],[2,]),'$end':([1,15,],[0,-1,]),'LEFT_PARENTESIS':([2,],[3,]),'STRING':([3,7,],[5,13,]),'COMMA':([4,5,10,11,12,13,14,],[7,-2,7,-7,-8,-9,-10,]),'RIGHT_PARENTESIS':([4,5,6,8,10,11,12,13,14,16,],[-6,-2,9,-5,-4,-7,-8,-9,-10,-3,]),'INT':([7,],[11,]),'FLOAT':([7,],[12,]),'IDENTIFIER':([7,],[14,]),'SEMICOLON':([9,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'first_arg':([3,],[4,]),'additional_args':([4,10,],[6,16,]),'empty':([4,10,],[8,8,]),'arg':([7,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINTF LEFT_PARENTESIS first_arg additional_args RIGHT_PARENTESIS SEMICOLON','statement',6,'p_statement','main.py',60),
  ('first_arg -> STRING','first_arg',1,'p_first_arg','main.py',65),
  ('additional_args -> COMMA arg additional_args','additional_args',3,'p_additional_args','main.py',69),
  ('additional_args -> COMMA arg','additional_args',2,'p_additional_args','main.py',70),
  ('additional_args -> empty','additional_args',1,'p_additional_args','main.py',71),
  ('empty -> <empty>','empty',0,'p_empty','main.py',80),
  ('arg -> INT','arg',1,'p_arg','main.py',84),
  ('arg -> FLOAT','arg',1,'p_arg','main.py',85),
  ('arg -> STRING','arg',1,'p_arg','main.py',86),
  ('arg -> IDENTIFIER','arg',1,'p_arg','main.py',87),
]
